services:
  api:
    build:
      context: ../great-reads-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../great-reads-api:/app
    env_file:
      - ../great-reads-api/.env # Assuming a .env file for API environment variables
    depends_on:
      - db

  client:
    build:
      context: ../great-reads-client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../great-reads-client:/app

  db:
    image: postgres:13-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: greatreads_db
      POSTGRES_USER: greatreads_user
      POSTGRES_PASSWORD: greatreads_password
    ports:
      - "5432:5432"

volumes:
  db_data:
